flows:
  ingest_haul:
    path_vm_local: PATH/TO/DATA  # path to local integrated data
    path_bio_files: BUCKET/trawl  # path to cloud trawl data
    cred_file: PATH/TO/.config/rclone/rclone.conf
    file_haul_info_all: haul_info_all.csv
    file_specimen_all: specimen_all.csv
    file_length_all: length_all.csv
    file_length_count_all: length_count_all.csv
    file_stratum_mean: stratum_mean.csv
    path_stratum_def: PATH/TO/resources/inpfc_def.csv

  ingest_NASC:
    path_vm_local: PATH/TO/DATA # path to local integrated data
    path_NASC_files: BUCKET/acoustics/NASC # path to cloud acoustic data
    cred_file: "PATH/TO/.config/rclone/rclone.conf"
    file_NASC_all: NASC_all.csv
    file_stratum_mean: stratum_mean.csv
    file_NASC_all_grid: NASC_all_griddify.geojson
    num_NASC_reprocess: 5
    new_file_num_limit: 200

  update_grid:
    path_vm_local: PATH/TO/DATA # path to local integrated data
    file_NASC_all_grid: NASC_all_griddify.geojson
    file_stratum_mean: stratum_mean.csv

  update_cache_MVBS:
    slice_mins: 180
    path_cache: "PATH/TO/CACHE"
    path_MVBS: "BUCKET/FOLDER/acoustics/MVBS"
    cred_file: "PATH/TO/.config/rclone/rclone.conf"
    file_MVBS_csv: MVBS_files.csv
    file_MVBS_zarr: latest_MVBS.zarr
